### ISSUE TITLE
Integration test bindings

### ISSUE THREAD

**Issue by greglook** [amperity/sparkplug#6]
An interesting idea that came up recently: provide a namespace which gives some utilities for rebinding the core spark API to something that performs the RDD actions locally, without invoking spark. This would allow for somewhat checking the correctness of spark job code without requiring a local spark context or other heavy machinery.

**Comment by brandonvin** [comment]
Closing stale issues. FWIW, it's pretty easy to test Spark locally by running a local in-process SparkSession (or SparkContext). Mocking the entire surface area of a SparkSession (or SparkContext) would only be feasible for the most trivial of Spark transformations anyway.
